# Generated by Django 5.2.1 on 2025-07-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='guests',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='guests',
            old_name='last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='guests',
            old_name='nick_Name',
            new_name='nick_name',
        ),
    ]
