# Generated by Django 5.2.1 on 2025-07-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0002_rename_first_name_attendee_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('reply', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendee',
            name='guests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding_rsvp.guest'),
        ),
        migrations.DeleteModel(
            name='Guests',
        ),
    ]
