# Generated by Django 5.2.1 on 2025-07-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0003_guest_alter_attendee_guests_delete_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='guests',
            new_name='guest',
        ),
    ]
