# Generated by Django 5.2.1 on 2025-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0004_rename_guests_attendee_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
