# Generated by Django 5.2.1 on 2025-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0005_guest_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='code',
        ),
        migrations.AddField(
            model_name='guest',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
