# Generated by Django 5.2.1 on 2025-09-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0006_remove_guest_code_guest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='message',
            field=models.TextField(default='Will Attend'),
        ),
    ]
