# Generated by Django 5.2.1 on 2025-09-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0007_alter_guest_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
