# Generated by Django 5.2.1 on 2025-09-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0008_delete_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='nick_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
