# Generated by Django 5.2.1 on 2025-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0010_alter_guest_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
