# Generated by Django 5.2.1 on 2025-09-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0012_alter_guest_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='nick_name',
        ),
    ]
