# Generated by Django 5.2.1 on 2025-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_rsvp', '0013_remove_guest_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
